- hosts: all
  tasks:
  - name: Install security updates, critical updates and update rollups
    ansible.windows.win_updates:
      category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
      use_scheduled_task: yes