- hosts: all
  tasks:
  - name: Install security updates
    ansible.windows.win_updates:
      category_names:
      - SecurityUpdates
      log_path: C:\updates.txt
      reboot: true
      reboot_timeout: 7200